Use cost factor of 10 for acceptance environment
This is the default and has proven sufficient for
executing on the micro instance the acceptance
environment is deployed to.

Attempting to use a cost factor of 16 appears to
cause unnecessary load on the server ultimately
resulting in the following error:

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://reeltime-acceptance-j7ket7rppg.elasticbeanstalk.com/api/account": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
grails.plugins.rest.client.RestBuilder.invokeRestTemplate(RestBuilder.groovy:307)
        at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:280)
        at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:268)
        at grails.plugins.rest.client.RestBuilder.post(RestBuilder.groovy:154)
        at helper.rest.AuthorizationAwareRestClient.doRequest(AuthorizationAwareRestClient.groovy:31)
        at helper.rest.AuthorizationAwareRestClient.post(AuthorizationAwareRestClient.groovy:18)
        at helper.test.ReelTimeClient.registerUser(ReelTimeClient.groovy:31)
        at in.reeltime.FunctionalSpec.registerUser(FunctionalSpec.groovy:111)
        at in.reeltime.FunctionalSpec.registerTestUser(FunctionalSpec.groovy:69)
        at in.reeltime.FunctionalSpec.setup(FunctionalSpec.groovy:65)
Caused by: java.net.SocketException: Unexpected end of file from server
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        ... 10 more